version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always